version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: waddles
      POSTGRES_PASSWORD: waddles
      POSTGRES_USER: waddles
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
