##### Permission Set
[[sets]]
    name = "base"
    description = "base commands"
    nodes = ["purge","ping"]

[[sets]]
    name = "resident"
    description = "residents"
    nodes = [
        "uptime"
    ]

[[sets]]
    name = "nitro_booster"
    description = "nitro booster"
    nodes = [
        "uptime",
        "nitro"
    ]

##### Permission groups

[[groups]]
    name = "The example group"
    description = "that one example group"
    role = "<discord role id>"
    sets = [
        "base"
    ]

[[groups]]
    name = "Resident"
    description = "them residents"
    role = "18975618273466762834"
    sets = [
        "base",
        "resident"
    ]
