##### Permission Set
[[sets]]
    name = "base"
    description = "base commands"
    nodes = ["purge","ping"]

[[sets]]
    name = "resident"
    description = "residents"
    nodes = ["uptime"]

[[sets]]
    name = "nitro_booster"
    description = "nitro booster"
    nodes = [
        "uptime",
        "nitro"
    ]

##### Permission groups

[[groups]]
    name = "Resident"
    description = "them residents"
    role = "772586405926797365"
    sets = [
        "base",
        "resident",
        "nitro_booster"
    ]


# File based because:
# - faster since its all in memory (lots of database includes queries, preloading would help this a lot though)
# - perms won't change much, only when adding new stuff or major changes
#   - could still have commands to add stuff ad-hoc