version: "3"
services:
  postgres:
    image: postgres
    restart: always
    env_file: production.env
    ports: 
      - 5432:5432
    volumes:
      - ${DB_LOCATION}:/var/lib/postgresql/data/:z
  bot:
    build: .
    restart: always
    env_file: production.env
    depends_on:
      - postgres
