version: '3'

vars:
  EXE: bin/waddles{{exeExt}}
  MAIN_CMD: ./cmd/waddles

tasks:
  default:
    cmds:
      - task -l
    silent: true 

  postgres-reset:
    desc: reset the postgres container's data volume
    cmds:
      - task: postgres-down
      - podman volume rm deploy_postgres_data
      - task: postgres-up

  postgres-down:
    desc: take down a container instance of postgres for development with 'task run'
    cmds:
      - podman-compose -f deploy/development-compose.yml down
      - rm .task/.pgup
    status:
      - "! test -f .task/.pgup"

  postgres-up:
    desc: put up a container instance of postgres for development with 'task run'
    cmds:
     - podman-compose -f deploy/development-compose.yml up -d
     - touch .task/.pgup
    status:
      - test -f ./.task/.pgup

  run:
    desc: run the bot locally wih
    deps: [postgres-up, build]
    cmds:
      -  ./{{.EXE}}

  test:
    desc: run all tests
    cmds:
      - go test ./... -cover -covermode atomic

  testv:
    desc: run all tests verbosely
    cmds:
      - go test ./... -cover -covermode atomic -v

  build:
    desc: build executable to {{.EXE}}
    cmds:
      - go build -o {{.EXE}} {{.MAIN_CMD}}
    sources:
      - ./**/*.go
    generates:
      - bin/waddles

  build-container:
    desc: builds an OCI-container for waddles
    cmds:
      - podman build -t waddles .

  todo:
    desc: find all //TODO comments in the repo
    cmds:
      - grep -nr --exclude="Taskfile.yml" --exclude-dir=".git" "//TODO" . 
